name: "Combined CI/CD, Security Scan & Release Notes"

on:
  push:
    branches:
      - master
      - SC-23484-release-notes

jobs:
  # Step 1: CI/CD
  ci-cd:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  # Step 2: Security Scan
  security-scan:
    needs: ci-cd
    if: always() && needs.ci-cd.outputs.successful_builds != ''
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.ci-cd.outputs.successful_builds) }}
    
    uses: ./.github/workflows/ecr-scheduled-security-scan.yml
    with:
      image: ${{ matrix.image }}
      tag: ${{ matrix.tag }}
      platforms: ${{ matrix.platforms }}
      image_type: ${{ matrix.image_type }}
      trigger_source: 'workflow'
    secrets: inherit

  # Step 3: Release Notes
  release-notes:
    needs: [ci-cd, security-scan]
    if: always() && !cancelled()
    uses: ./.github/workflows/release-notes.yml
    with:
      ci_job_id: ${{ needs.ci-cd.outputs.build_job_id }}
    secrets: inherit