name: ECR Jenkins Vulnerability Scan

on:
  workflow_dispatch:  # 👈 keeps workflow valid but disables automatic triggers. See below
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      tag:
        required: true
        type: string
      platforms:
        required: true
        type: string
      image_type:
        required: true
        type: string
      trigger_source:
        type: string
        required: false
        default: 'workflow'
  # Disabled automatic triggers until results of discussion with Secirity team
  # schedule:
  #   - cron: '0 0 * * *'
  # push:
  #   branches:
  #     - master

jobs:
  vulnerability-detection:
    strategy:
      fail-fast: false
      matrix:
        include:
          ### Jenkins 2.4
          - image: "2.492.3/Dockerfile"
            tag: "2.492.3"
            platforms: "linux/amd64"
            image_type: "Jenkins"

    uses: spryker-projects/gha-reusable-workflows/.github/workflows/ecr-scheduled-security-scan.yml@main
    with:
      image: ${{ matrix.image }}
      tag: ${{ matrix.tag }}
      platforms: ${{ matrix.platforms }}
      image_type: ${{ matrix.image_type }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ECR_REPO: ${{ secrets.AWS_ECR_REPO }}
      SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_CE_SECURITY_SCAN_JENKINS }}
