name: ECR Jenkins Vulnerability Scan

on:
  workflow_dispatch  # 👈 keeps workflow valid but disables automatic triggers. See below
  ### Disabled automatic triggers until results of discussion with Secirity team
  # schedule:
  #   - cron: '0 0 * * *'
  # push:
  #   branches:
  #     - master

jobs:
  vulnerability-detection:
    strategy:
      fail-fast: false
      matrix:
        include:
        ### Leaving only latest image. Details - https://spryker.atlassian.net/browse/SC-22221
          # ### Jenkins 2.1
          # - image: "2.176/Dockerfile"
          #   tag: "2.176"
          #   platforms: "linux/amd64"
          #   image_type: "Jenkins"

          # ### Jenkins 2.3
          # - image: "2.305/Dockerfile"
          #   tag: "2.305"
          #   platforms: "linux/amd64"
          #   image_type: "Jenkins"
          # - image: "2.324/Dockerfile"
          #   tag: "2.324"
          #   platforms: "linux/amd64"
          #   image_type: "Jenkins"

          # ### Jenkins 2.4
          # - image: "2.401/Dockerfile"
          #   tag: "2.401"
          #   platforms: "linux/amd64"
          #   image_type: "Jenkins"
          # - image: "2.442/Dockerfile"
          #   tag: "2.442"
          #   platforms: "linux/amd64"
          #   image_type: "Jenkins"
          - image: "2.488/Dockerfile"
            tag: "2.488"
            platforms: "linux/amd64"
            image_type: "Jenkins"

    uses: spryker-projects/gha-reusable-workflows/.github/workflows/ecr-scheduled-security-scan.yml@main
    with:
      image: ${{ matrix.image }}
      tag: ${{ matrix.tag }}
      platforms: ${{ matrix.platforms }}
      image_type: ${{ matrix.image_type }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ECR_REPO: ${{ secrets.AWS_ECR_REPO }}
      SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_CE_SECURITY_SCAN_JENKINS }}
